# Generated by Django 4.0.6 on 2022-08-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_alter_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(default='Bench', max_length=100),
        ),
    ]
